version: "3"
services:
  # rust:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis
  #     - mail

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  # mail:
  #   image: bytemark/smtp
  #   restart: always
  #   environment:
  #     RELAY_HOST: smtp.example.com
  #     RELAY_PORT: 587
  #     RELAY_USERNAME: alice@example.com
  #     RELAY_PASSWORD: secretpassword
  #     RELAY_AUTH_METHOD: LOGIN

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - pgadmin.env

    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
  pgadmin-data:
    driver: local